on: [push]

jobs:
   hello_world_job:
         runs-on: ubuntu-latest
         name: A job to say hello to
         steps:
            - uses: actions/checkout@v3
            - id: foo
              uses: pratikkuma/test_composite_settings_pratik@v1
              with:
                 who-to-greet: 'Mona the Octocat'
            - run: echo random-number ${{ steps.foo.outputs.random-number }}
              shell: bash
